#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
sudo apt update > /dev/null
sudo apt install nginx -y > /dev/null

if ! pgrep nginx &> /dev/null; then
    exit 1
fi

if ! nc -z localhost 80; then
    exit 1
fi

sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        return 200 "Hello World!\n";
    }
}
EOF'
sudo nginx -s reload > /dev/null
