#!/usr/bin/env bash
# Bash Script to automate,configure and fix my code

if ! command -v nginx &> /dev/null; then
    sudo apt update
    sudo apt install nginx -y
fi

if ! systemctl is-active --quiet nginx; then
    sudo systemctl start nginx
fi

if ! grep -q "listen\s*80;" /etc/nginx/nginx.conf; then
    sudo sed -i 's/#\?\(listen\s*\)80;/\1 80;/g' /etc/nginx/nginx.conf
fi
sudo systemctl restart nginx
