#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.backup
{
	echo "127.0.0.2    localhost"
	echo "8.8.8.8    facebook.com"
} > ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
sudo service networking restart
