#!/usr/bin/env bash

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
id -u nginx &>/dev/null || useradd -r -d /var/www -s /sbin/nologin nginx
nginx -t
service nginx stop
service nginx start
