#!/usr/bin/env bash

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
if ! id -u nginx > /dev/null 2>&1
then useradd -r -d /var/www -s /sbin/nologin nginx
fi
nginx -t && service nginx restart
